# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b20894a1fd38f64168f52ea121dc73e2a913c02160b7a1979e16d3b5be04563110552a9566ed624bb28b8eff3f8e456b55ed172df5dca7a88ebe509513502178

test:
  secret_key_base: 5915efb51545e856bffd1d9f81ce9464c0ca474f3c1d791b766c8d7cc8cd0bc79fe120f7488fa6201632b6d656932de98585a3ffbca316bc33e955a0bfba932e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
